name = "itah-me"
main = "src/index.js"
compatibility_date = "2025-01-01"
workers_dev = true

routes = [
  { pattern = "itah.me", custom_domain = true },
  { pattern = "www.itah.me", custom_domain = true }
]
[[rules]]
type = "Text"
globs = ["**/*.css"]
